%TAG !env! tag:yaml.org,2002:python/name:
---
llm:
  provider: "openai"  # ollama // openai
  model: "gpt-4o-mini" # phi // llama3 // gpt-3.5-turbo // gpt-4o-mini
  url: "http://localhost:11434"  # ollama default host http://localhost:11434
  api-key: ${LLM_API_KEY}
